Add deprecation warning to collate functions
lightly-ai/lightly pull request #1079
Opened 2023-02-24 09:44 UTC by Ra1Nik

After https://github.com/lightly-ai/lightly/pull/1068, the old collate functions will be deprecated. Add deprecation warning.

2023-02-24 15:13 UTC, philippmwirth requested changes

2023-02-24 15:13 UTC, philippmwirth commented on lightly/data/collate.py
> +        warn(
Can you add this function to the bottom of the file and then use it wherever you need it:
```python
def _deprecation_warning_collate_functions() -> None:
    warn(
        "Collate functions are deprecated and will be removed in favor of transforms in v1.4.0.\n"
        "Please use MultiViewCollate in `lightly.data.multi_view_collate` together with the correct transform for your model instead.\n"
        "See https://docs.lightly.ai/self-supervised-learning/examples/models.html for examples."
        category=DeprecationWarning,
    )
```

I'm not super happy with the wording. Maybe you can improve.

Note the change to `DeprecationWarning` for better visibility.

2023-02-24 15:46 UTC, philippmwirth reviewed
Awesome! I'm not approving yet because of the dependency between this PR and the others but you can consider the issue done 👍

2023-03-21 12:05 UTC, guarin commented
@philippmwirth could you approve?

2023-03-21 12:12 UTC, philippmwirth approved these changes

2023-03-21 12:15 UTC, merged