Add support for MoCo v3
lightly-ai/lightly pull request #1163
Opened 2023-04-24 18:45 UTC by adamjstewart

Exact same design as #1150. Should we just subclass one in the other?

I'll let you decide whether you want to default to v1/2 or v3 hyperparams.

Reference implementations:

* v1 and v2: https://github.com/facebookresearch/moco/blob/main/moco/builder.py#L34
* v3: https://github.com/facebookresearch/moco-v3/blob/main/moco/builder.py#L36

2023-04-25 06:36 UTC, philippmwirth requested changes
Hi @adamjstewart thanks a lot for contributing. The changes look great 🙂

The only thing we still need to do is update the projection heads used in the benchmarks, see:

https://github.com/lightly-ai/lightly/blob/0d26bd257e8699a2bf6dc825863515377b934189/docs/source/getting_started/benchmarks/imagenet100_benchmark.py#L222

https://github.com/lightly-ai/lightly/blob/0d26bd257e8699a2bf6dc825863515377b934189/docs/source/getting_started/benchmarks/imagenette_benchmark.py#L317

You can simply replace the hidden dimension and the output dimension with the default values of MoCoV3.

2023-04-25 06:36 UTC, philippmwirth commented on lightly/models/modules/heads.py
> +        num_layers: int = 2,
This should be 3 for v3 I believe.

2023-04-25 07:43 UTC, philippmwirth commented on lightly/models/modules/heads.py
> +        num_layers: int = 2,
I just discussed this with @guarin and changing the defaults will change user code so we'd prefer to use the v2 settings as default values for now.

2023-04-25 15:56 UTC, adamjstewart commented
Let me know if you also want me to change the defaults for SimCLR from v2 to v1.

2023-05-02 11:09 UTC, philippmwirth approved these changes
Thanks for the changes!

2023-05-02 11:09 UTC, merged