Replace multiviewcolllate with default collate
lightly-ai/lightly pull request #1262
Opened 2023-05-31 07:22 UTC by philippmwirth

2023-05-31 15:17 UTC, guarin commented
Didn't review yet but could you update the message here?
```
./lightly/data/collate.py:        "Please use MultiViewCollate in `lightly.data.multi_view_collate` together with the correct transform for your model instead.\n"
```

2023-06-01 07:57 UTC, philippmwirth commented
> Didn't review yet but could you update the message here?
> 
> ```
> ./lightly/data/collate.py:        "Please use MultiViewCollate in `lightly.data.multi_view_collate` together with the correct transform for your model instead.\n"
> ```

Done!

2023-06-02 07:57 UTC, guarin requested changes
Thanks! Not sure if the pascal VOC dataset works as expected but otherwise looks good :)

2023-06-02 07:57 UTC, guarin commented on examples/pytorch/dino.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Are you sure that the `target_transform` part is not required anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch/mae.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch/msn.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch/swav.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch/swav_queue.py
>  )
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch/vicregl.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning/dino.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning/msn.py
>  )
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning/pmsn.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning/pmsn.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning/swav_queue.py
>  )
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning/vicregl.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning_distributed/mae.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning_distributed/msn.py
>  )
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning_distributed/pmsn.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning_distributed/simmim.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning_distributed/swav.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 07:57 UTC, guarin commented on examples/pytorch_lightning_distributed/vicregl.py
> +)
```suggestion
dataset = torchvision.datasets.VOCDetection(
    "datasets/pascal_voc", download=True, transform=transform
)
```

Is `target_transform` not needed anymore?

2023-06-02 09:02 UTC, philippmwirth commented on examples/pytorch_lightning/dcl.py
> +from lightly.loss import DCLLoss
Yes I know but it's strange to import something that isn't used.

2023-06-02 09:02 UTC, philippmwirth commented on examples/pytorch/barlowtwins.py
> -from lightly.data import LightlyDataset
I'd like to remove it as I think it's cleaner.

2023-06-02 14:35 UTC, merged