Igor lig 3059 add dcl dclw imagenet benchmark
lightly-ai/lightly pull request #1302
Opened 2023-07-01 07:58 UTC by IgorSusmelj

2023-07-10 06:31 UTC, IgorSusmelj commented
From the paper (https://arxiv.org/pdf/2110.06848.pdf):

> result on ImageNet-1K using linear evaluation. With DCL, SimCLR can achieve 64.6% top-1 accuracy with only 100 epochs compared to SimCLR baseline: 57.5%;

- @guarin, which SimCLR version did we benchmark so far? It can't be the original one as our accuracy is much higher `63.2` vs `57.5`.

Both, the original SimCLR paper and the DCL paper refer to the experiment with batch size 256 and training for 100 epochs which results in `57.5` accuracy for linear evaluation.

2023-07-10 15:21 UTC, guarin commented
It is the original one but with square root lr scaling, see appendix B.1 in the paper:
![Screen Shot 2023-07-10 at 17 20 36](https://github.com/lightly-ai/lightly/assets/43336610/835b06a6-94f6-450a-b610-1d020e9556bf)

2023-07-10 19:49 UTC, IgorSusmelj commented
> It is the original one but with square root lr scaling, see appendix B.1 in the paper: ![Screen Shot 2023-07-10 at 17 20 36](https://user-images.githubusercontent.com/43336610/252386519-835b06a6-94f6-450a-b610-1d020e9556bf.png)

Ok, in the paper they state that they use the default settings 
<img width="503" alt="image" src="https://github.com/lightly-ai/lightly/assets/1522766/7c46a712-bd34-443e-a6fe-22975ca8fcc4">

Let's do the following. 
- We update the SimCLR ImageNet code to use linear lr and call it SimCLRv1. We add a comment that one could also use square root learning rate for the model and get slightly better results for smaller batch sizes/fewer epochs
- We make a SimCLRv2 version that uses the modifications from the follow up paper (3 layer projection head etc.)
- I'll then rerun the experiments for DCL and DCLW to use SimCLRv1. the SimCLR models are trained quickly.

In the future we should be more careful with the reference implementations. If we don't follow the settings in the paper we will have issues with all the other papers that build up on the previous one.

2023-07-11 07:03 UTC, guarin commented
> In the future we should be more careful with the reference implementations. Maybe we review the PRs and check for the parameters before we start the training run. If we don't follow the settings in the paper we will have issues with all the other papers that build up on the previous one.

We have chosen those parameters on purpose because the paper reported that those work best for small batch sizes. There are also comments in the code for the relevant parameters, why they were chosen, and what to do for larger batch sizes. We also did the same for the other models. Just using default parameters without adjusting for batch size/epochs results in bad performance for most models and I don't think this is helpful as the reported numbers wouldn't allow a fair comparison between the different methods. If we truly want to reproduce the models we also have to use the same batch size and training epochs.

> We make a SimCLRv2 version that uses the modifications from the follow up paper (3 layer projection head etc.)

Could you add an issue for it?

> I'll then rerun the experiments for DCL and DCLW to use SimCLRv1. the SimCLR models are trained quickly.

Sure

> I'd not discard the current results but put them to a section of "additional experiments". I'd also drop all the others we did. E.g. the BYOL one with the wrong learning rate. It would be a pity to discard the results completely.
 
I think it is ok to leave them in the PR, otherwise this will be super hard to maintain.

2023-07-11 13:59 UTC, IgorSusmelj commented
I understand your points. How about at least marking them in the readme?
Something like this
<img width="857" alt="image" src="https://github.com/lightly-ai/lightly/assets/1522766/6a8340b2-a109-45bf-80c9-2a54f6c5a241">

2023-07-11 14:01 UTC, guarin commented
> I understand your points. How about at least marking them in the readme? Something like this @guarin

I like it! Maybe we could even add a `See Appendix B.1 in [SimCLR paper](https://arxiv.org/abs/2002.05709)`.

2023-07-14 09:41 UTC, guarin requested changes
The code and results LGTM!

Could you add the results also to the benchmarks docs?

2023-07-14 09:41 UTC, guarin commented on benchmarks/imagenet/resnet50/main.py
> +    "dclw": {"model": dclw.DCLW, "transform": simclr.transform},
```suggestion
    "dcl": {"model": dcl.DCL, "transform": dcl.transform},
    "dclw": {"model": dclw.DCLW, "transform": dclw.transform},
```

Could you also move them to the top of the dict? Then everything stays alphabetically sorted.

2023-07-14 12:31 UTC, guarin approved these changes
One last thing but I'll already approve

2023-07-14 12:31 UTC, guarin commented on benchmarks/imagenet/resnet50/main.py
> +    "dclw": {"model": dclw.DCLW, "transform": simclr.transform},
```suggestion
    "dcl": {"model": dcl.DCL, "transform": dcl.transform},
    "dclw": {"model": dclw.DCLW, "transform": dclw.transform},
```

2023-07-14 13:14 UTC, IgorSusmelj commented on benchmarks/imagenet/resnet50/main.py
> +    "dclw": {"model": dclw.DCLW, "transform": simclr.transform},
I changed that!

2023-07-14 13:14 UTC, merged