new specs with correct v3
lightly-ai/lightly pull request #1426
Opened 2023-11-13 09:17 UTC by japrescott

regenerate the specs with correct v3

2023-11-13 09:28 UTC, MalteEbner requested changes
Please remove all `__init__.py-e` files

2023-11-13 09:55 UTC, MalteEbner approved these changes
Generation looks good.

2023-11-20 14:40 UTC, guarin commented on tests/api_workflow/test_api_workflow_compute_worker.py
I think there is another test that has to be updated around line 218 (`test_selection_config`). It should also use the new `V3` classes. When merging this PR we should not have to import any of the old `SelectionCon`

2023-11-20 14:48 UTC, guarin requested changes
Nice! I think one more tests needs to be changed but otherwise this looks good to me :)

2023-11-20 14:48 UTC, guarin commented on tests/api_workflow/test_api_workflow_compute_worker.py
> +)
Sorry, I forgot to mention this, but we usually import the swagger generated classes directly from `swagger_client.models` like this:
```
from lightly.openapi_generated.swagger_client.models import (
    SelectionConfigV3,
    SelectionConfigV3Entry,
    ...
)

It makes the code a bit easier to read, the drawback is that the VSCode auto-import function does not use this format.

2023-11-21 08:16 UTC, guarin approved these changes
One last small thing otherwise everything LGTM! I already approved so you can merge whenever you are ready :)

2023-11-21 08:16 UTC, guarin commented on tests/api_workflow/test_api_workflow_compute_worker.py
>                              type=SelectionStrategyType.SIMILARITY,
Could you update `SelectionStrategyType` also to `SelectionStrategyTypeV3`?

2023-11-22 08:17 UTC, merged