Implement W-MSE Loss and Transform
lightly-ai/lightly pull request #1459
Opened 2023-12-17 19:14 UTC by johnsutor

This pull request implements the W-MSE Transform and W-MSE Loss as proposed in the paper https://arxiv.org/pdf/2007.06346.pdf. The code largely comes from the original repository https://github.com/htdt/self-supervised, preserving the default hyperparameters with some minor changes to make it compatible with lightly. This feature was recommended in this issue: https://github.com/lightly-ai/lightly/issues/1424#event-11223331529

2023-12-18 07:27 UTC, philippmwirth commented
Hi @johnsutor, thank you very much for your contribution. Someone from our team will have a look asap.

2023-12-18 09:02 UTC, philippmwirth requested changes
Thank you for the changes, @johnsutor! The PR looks great so far. I have left a few comments on things I think we should change before merging. If you have any questions or require help updating the PR please let me know 🙂

2023-12-18 13:38 UTC, johnsutor commented on tests/loss/test_WMSELoss.py
> +        print(loss)
Sorry I left those!

2023-12-18 13:38 UTC, johnsutor commented on lightly/loss/wmse_loss.py
> +    running_mean: torch.Tensor
Precisely, will do.

2023-12-18 13:54 UTC, johnsutor commented on lightly/loss/wmse_loss.py
> +        embedding_dim: int = 64,
Just double checked https://arxiv.org/pdf/2007.06346.pdf, and in the experiment implementation details, they list that they set the embedding_dim to be 128 for imagenet. I'll change it to 128 if that's OK.

2023-12-18 14:52 UTC, johnsutor commented on lightly/transforms/wmse_transform.py
> +                T.RandomHorizontalFlip(p=hf_prob),
Based on the results from here: https://stackoverflow.com/questions/62968174/for-pil-imagefilter-gaussianblur-how-what-kernel-is-used-and-does-the-radius-par I opted to stick with the default GaussianBlur transform already in lightly.

2023-12-18 15:26 UTC, johnsutor commented on lightly/loss/wmse_loss.py
> +        embedding_dim: int = 64,
Also changing the default w_size based on this line from the paper:

> Next,each partition is further split in sub-batches, using the heuristic that the size of each sub-batch (Vi) should be equal to the size of embedding (|v|) times 2 (this prevents instability issues when computing the covariance matrices).

2023-12-19 07:22 UTC, philippmwirth commented on lightly/loss/wmse_loss.py
> +        embedding_dim: int = 64,
Thanks!

2023-12-19 07:23 UTC, philippmwirth approved these changes
This looks good now! I'll quickly do a sanity check on Cifar10 and then we're good to merge. Thank you 🙂

2023-12-19 08:35 UTC, philippmwirth commented
The results look promising, after 3 epochs we get a kNN accuracy of over 50% with `num_samples=4` and SimCLR projection head.
```
------------------------------------------------------------------------------------------
| Model         | Batch Size | Epochs |  KNN Test Accuracy |       Time | Peak GPU Usage |
------------------------------------------------------------------------------------------
| WMSE          |        512 |      3 |              0.519 |   12.9 Min |      9.4 GByte |
------------------------------------------------------------------------------------------
```
Will merge this now and leave the proper benchmarking for later. @guarin FYI.

2023-12-19 08:42 UTC, merged