upgrade requirements/base.txt minimum numpy version to 1.20 for typing
lightly-ai/lightly pull request #1490
Opened 2024-01-30 12:51 UTC by MalteEbner

We are using the `numpy.typing` subpackage, which is only available in numpy >= 1.20: https://numpy.org/devdocs/reference/typing.html#module-numpy.typing

Thus we need to update the minimum requirement.

2024-01-30 13:42 UTC, IgorSusmelj requested changes
Let's not merge this as of now. We need a proper strategy to deal with the dependencies.

For context:
- We just added https://github.com/lightly-ai/lightly/blob/master/requirements/minimal_requirements.txt which contains the actual minimum requirements needed to use all the features. We have a new test for this in the CI pipeline
- We did not want to change all the base requirements yet, as we have many users using only very specific features due to the modular way lightly works. We will have to figure out how we want to deal with that. The issue is that we accidentally broke many requirements because our previous tests were always installing latest packages. So we never tested if the requirements we once established are still valid or not.

2024-01-30 13:43 UTC, japrescott requested changes
lets quickly review the minimum requirements

2024-07-02 15:40 UTC, SauravMaheshkar commented
How does https://github.com/lightly-ai/lightly/pull/1559 affect this ?

2024-07-10 11:10 UTC, guarin commented
@MalteEbner what is the state of this PR?

IMO there are two options:
* Handle `from numpy.typing import NDArray` depending on whether it is available or not. If it is not available we could define a generic alias for `NDArray` instead. Not sure how that would work for older Python versions though.
* Increase minimal numpy version in `pyproject.toml`. Numpy 1.18 has reached end of life >2 years ago.

The current state with `numpy>=1.18.1, <2` as [default requirement](https://github.com/lightly-ai/lightly/blob/6ebde88201ff8e647a809221617f2cf76ae81554/pyproject.toml#L41) and `numpy==1.26.6` as [minimal requirement](https://github.com/lightly-ai/lightly/blob/6ebde88201ff8e647a809221617f2cf76ae81554/pyproject.toml#L95C4-L95C17) is not ideal.

2024-08-08 08:12 UTC, guarin commented
This has been fixed in https://github.com/lightly-ai/lightly/pull/1625

We still support numpy<1.20 and only import from numpy.typing when type-checking.

2024-08-08 08:12 UTC, closed without merging