docs: update datasets tutorial
lightly-ai/lightly pull request #1569
Opened 2024-07-01 14:54 UTC by SauravMaheshkar

This PR aims to update and refactor Tutorial 1 "Structure your Input"

2024-07-02 15:10 UTC, MalteEbner reviewed
Looks good, I like it!

What I am most unsure about: Did you try actually feeding a `hf_dataloader` into the Lightly SSL training scripts? They might be incompatible, as the Lightly SSL training scripts expect a (batch, targets, filenames) dataloader output, which is not provided by huggingface.

2024-07-02 15:10 UTC, MalteEbner commented on docs/source/tutorials/structure_your_input.rst
> +    hf_dataloader = torch.utils.data.DataLoader(base["train"])
I would make the function shorter.
```suggestion
    import torch
    from typing import Any
    from datasets import load_dataset
    from lightly.transforms import SimCLRTransform

    base = load_dataset("uoft-cs/cifar10", trust_remote_code=True)

    ## Use pre-defined set of transformations from Lightly SSL
    transform = SimCLRTransform()

    def apply_transform(batch: dict[str, Any], transform=transform)-> Dict[str, Any]:
        """
        Applies the given transform on all elements of batch["image"].
        """
        assert "image" in example_batch, "batch must contain key 'image'"
        batch["image"] = [transform(img.convert("RGB")) for img in batch["image"]]
        return batch

    base.set_transform(apply_transform)

    hf_dataloader = torch.utils.data.DataLoader(base["train"])
```

2024-07-04 21:47 UTC, SauravMaheshkar commented on docs/source/tutorials/structure_your_input.rst
> +the `torchvision.data <https://pytorch.org/vision/main/datasets.html>`_ submodule provides a robust implementation for most use cases,
It seems like there was some miscommunication here. I didn't mean to convey that torchvision is "experimental", but rather that torchvision hosts a lot of smaller datasets which can be loaded on-device for verifying training pipelines on smaller datasets.

2024-07-04 21:48 UTC, SauravMaheshkar commented on docs/source/tutorials/structure_your_input.rst
> +When you have your own data in memory, the ability to quickly create datasets and dataloaders is of prime importance.
Thanks, makes sense.

2024-07-04 21:57 UTC, SauravMaheshkar commented on docs/source/tutorials/structure_your_input.rst
> +    hf_dataloader = torch.utils.data.DataLoader(base["train"])
Thank you, that is much cleaner 🧼

2024-07-04 22:34 UTC, SauravMaheshkar commented
> g scripts? They might be incompatible, as the Lightly SSL training scripts expect a (batch, targets, filenames) dataloader output, which is not provided by huggingface.

Yes, I've tried it out and it does work with Lightly Training Scripts. The Colab Notebook released with the recent vector index blogpost uses the food101 dataset from the Huggingface for training.

2024-07-05 11:35 UTC, MalteEbner approved these changes
Looks good from my side :)

2024-07-05 12:44 UTC, guarin requested changes
Thanks for adding all this helpful information! I left a bunch of comments, mostly regarding structure and formatting.

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +Huggingface with the Lightly SSL open-source package. We will also look into how we can create dataloaders
```suggestion
Huggingface with Lightly SSL. We will also look into how we can create dataloaders
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +----------------------------
```suggestion
LightlyDataset
--------------
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +It allows us to create both Image and Video dataset classes with or without labels.
```suggestion
It allows us to create both image and video dataset classes with or without labels.
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +Creating an Unlabeled Image Dataset is the simplest and the most common use case.
```suggestion
Creating an unlabeled image dataset is the simplest and the most common use case.
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +Assuming all images are in a single directory, you can simply pass in the path to the directory containing all the images, viz.
```suggestion
Assuming all images are in a single directory, you can simply pass in the path to the directory containing all the images.
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +In this blog post, we will provide a brief overview of the `LightlyDataset <https://docs.lightly.ai/self-supervised-learning/lightly.data.html#lightly.data.dataset.LightlyDataset>`_
```suggestion
In this tutorial, we will provide a brief overview of the `LightlyDataset <https://docs.lightly.ai/self-supervised-learning/lightly.data.html#lightly.data.dataset.LightlyDataset>`_
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
>  `PyAV <https://github.com/PyAV-Org/PyAV>`_. The following formats are supported.
```suggestion
Lightly SSL uses
`torchvision <https://github.com/pytorch/vision>`_ and
`PyAV <https://github.com/PyAV-Org/PyAV>`_ for video loading. The following formats are supported.
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +and the dataset class will assign each image its subdirectory as label., viz.
```suggestion
and the dataset class will assign each image its subdirectory as label.
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +   labeled_dataset = LightlyDataset(input_dir='labeled_images_dir/')
```suggestion
   labeled_dataset = LightlyDataset(input_dir='labeled_image_dir/')
```

Please also rename the `data/` dir in the example directory structure to `labeled_image_dir`

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +you can simply pass the path into the LightlyDataset constructor.
Please rename `data/` in example directory structure to `video_dir/`

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +   To use video-specific features of Lightly SSL download the necessary extra dependencies `pip install lightly"[video]"`. Furthermore,
```suggestion
   To use video-specific features of Lightly SSL download the necessary extra dependencies `pip install "lightly[video]"`. Furthermore,
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +(Bootstrap your own element) expects two views of an input image. To achieve this, we can use the `BYOLTransform`
```suggestion
Just create a dataset as you normally would and apply transforms for greater control over the dataloader. For example, the BYOL self-supervised learning method expects two views of an input image. To achieve this, we can use the `BYOLTransform`
```

You could also make BYOL link to the BYOL docs.

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +while creating the dataset instance, which will lead to the dataloader returning two views per batch, viz.
```suggestion
while creating the dataset instance, which will lead to the dataloader returning two views per batch.
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +   from lightly.transforms.byol_transform import (
```suggestion
   from lightly.transforms import (
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +   )
BYOL is maybe not a great example as it requires more boilerplate code for creating the transformer compared to SimCLR. Consider switching to SimCLR

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +       # ...
I don't think this part is necessary, we also don't show it for LightlyDataset

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +HuggingFace Datasets
```suggestion
Hugging Face Datasets
```

Please also correct in other places on this page

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +To use a dataset from the huggingface hub 🤗, we can simply apply the desired transformations using the
```suggestion
To use a dataset from the Hugging Face Hub 🤗, we can simply apply the desired transformations using the 
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +    base = load_dataset("uoft-cs/cifar10", trust_remote_code=True)
```suggestion
    dataset = load_dataset("uoft-cs/cifar10", trust_remote_code=True)
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +    def apply_transform(batch: dict[str, Any], transform=transform)-> Dict[str, Any]:
```suggestion
    def apply_transform(batch: Dict[str, Any])-> Dict[str, Any]:
```
Also make sure to import `Dict` from typing

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +    hf_dataloader = torch.utils.data.DataLoader(base["train"])
```suggestion
    dataset.set_transform(apply_transform)
    dataloader = torch.utils.data.DataLoader(dataset["train"])
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +`transforms <https://docs.lightly.ai/self-supervised-learning/lightly.transforms.html>`_ submodule while creating our datasets, viz.
```suggestion
We can use off the shelf augmentations from libraries like `torchvision transforms <https://pytorch.org/vision/stable/transforms.html>`_
and `albumentations <https://albumentations.ai/docs/>`_ or the ones offered by Lightly SSL's
`transforms <https://docs.lightly.ai/self-supervised-learning/lightly.transforms.html>`_ submodule while creating our datasets.
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +    dataset = LightlyDataset(input_dir='image_dir/')
I would also include a transform here as we show transforms also for pytorch and hugging face.

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +   You can also create your own augmentations, for more details please refer to :ref:`lightly-custom-augmentation-5`
```suggestion
   You can also create your own SSL augmentations, for more details please refer to :ref:`lightly-custom-augmentation-5` 
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +    albumentation_transforms = A.Compose(
```suggestion
    albumentation_transform = A.Compose(
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +    torchvision_transforms = T.Compose(
```suggestion
    torchvision_transform = T.Compose(
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +    )
I think these two sections are a bit overkill as they are quite verbose but do not add much new information. I would replace them and just mention that we can use the transforms for any dataset as shown previously and give a minimal example like:
```
dataset = LightlyDataset(input_dir="image_dir/", transform=torchvision_transform)
# or
dataset = torchvision.datasets.CIFAR10("datasets/cifar10", download=True, transform=albumentations_transform)
```

2024-07-05 12:44 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +In this blogpost, we went through examples of using various open-source packages to create datasets and dataloaders with Lightly SSL,
```suggestion
In this tutorial, we went through examples of using various open-source packages to create datasets and dataloaders with Lightly SSL,
```

2024-07-08 09:30 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +    dataset = LightlyDataset(input_dir='image_dir/')
This hasn't been addressed yet

2024-07-08 09:35 UTC, guarin reviewed
Looks great! Two small things left and then we can merge :)

2024-07-08 09:35 UTC, guarin commented on docs/source/tutorials/structure_your_input.rst
> +    dataset = LightlyDataset(input_dir="image_dir/", transform=torchvision_transform)
Suggestion to make it more evident that datasets/transforms are interchangeable:

```suggestion
    
    # Datasets and transforms can be mixed and matched together:
    dataset = LightlyDataset(input_dir="image_dir/", transform=torchvision_transform)
    dataset = torchvision.datasets.CIFAR10("datasets/cifar10", transform=lightly_transform)
```

2024-07-08 11:12 UTC, guarin approved these changes
LGTM! Thanks a lot!

2024-07-08 11:20 UTC, merged