Adding type check for serve.py
lightly-ai/lightly pull request #1652
Opened 2024-09-23 10:19 UTC by ishaanagw

2024-09-23 10:26 UTC, ishaanagw commented
Hey @philippmwirth, please review this MR. Thanks.

2024-09-23 16:56 UTC, SauravMaheshkar approved these changes
LGTM ❤️

2024-09-23 16:58 UTC, SauravMaheshkar commented
Partly fixes #1635

2024-09-23 17:04 UTC, ishaanagw commented
Hey, thanks, very new to this open source, can you also merge it ? or do you guys follow some release timelines ?

2024-09-23 17:07 UTC, SauravMaheshkar commented
> Hey, thanks, very new to this open source, can you also merge it ? or do you guys follow some release timelines ?

Hello 👋🏽 , I think in order for this PR to count for your Hacktoberfest total we'd have to merge it between Oct 1-31. I'm going to wait on @guarin for this.

2024-09-23 17:14 UTC, ishaanagw commented
Ohh, but I am not doing it for hacktober fest, so if you can merge it then please go ahead, Thanks.

2024-09-24 10:07 UTC, guarin requested changes
Thanks a lot for the PR! There is one small thing that needs changing before we can merge it, sorry for the annoyance. I'll update the issue description to reflect that we need older type hints.

2024-09-26 13:52 UTC, ishaanagw commented on lightly/api/serve.py
> +        def send_response_only(self, code: int, message: str | None = None) -> None:
okay, will add and crate a PR

2024-09-26 13:54 UTC, guarin commented on lightly/api/serve.py
> +        def send_response_only(self, code: int, message: str | None = None) -> None:
No need to create a new PR, you can just update this one.

2024-10-02 08:38 UTC, guarin commented
@ishaanagw do you need help with the PR? I can also update to get it merged :)

2024-10-03 12:24 UTC, ishaanagw commented on lightly/api/serve.py
> +        def send_response_only(self, code: int, message: str | None = None) -> None:
Added the future annotation import, please review, Thanks

2024-10-03 12:37 UTC, SauravMaheshkar commented on lightly/api/serve.py
> +        def send_response_only(self, code: int, message: str | None = None) -> None:
Could you run `isort` so that CI passes for formatting checks. You can run `make format` to format all files.

2024-10-03 12:51 UTC, ishaanagw commented on lightly/api/serve.py
> +        def send_response_only(self, code: int, message: str | None = None) -> None:
Fixed it, please check

2024-10-03 13:09 UTC, guarin approved these changes
Awesome, thanks!

2024-10-03 13:09 UTC, merged