Addition of RFFT2D and IRFFT2D transforms
lightly-ai/lightly pull request #1662
Opened 2024-10-03 06:45 UTC by snehilchatterjee

**Modified Components:**
- `lightly/transforms/__init__.py`

**New Files:**
- `lightly/transforms/irfft2d_transform.py`
- `lightly/transforms/rfft2d_transform.py`

**Enhancement:**
- Added support for RFFT2D and IRFFT2D transforms.

**Fixes Issue:**
- Closes #1656 and #1657

2024-10-03 08:29 UTC, guarin requested changes
Thanks, this looks great!

Could you also add tests for each transform? You can add:
* `tests/transforms/test_rfft2d_transform.py`
* `tests/transforms/test_irfft2d_transform.py`

They should look like this:
```
def test():
    transform = RFFT2DTransform()
    image = torch.rand(3, 32, 32)
    output = transform(image)
    assert output.shape == # Put expected shape here
```

Regarding the formatting check, you can run `make run` to format everything.

2024-10-03 08:29 UTC, guarin commented on lightly/transforms/rfft2d_transform.py
> +        self.to_pil = transforms.ToPILImage()
We shouldn't add `to_tensor` and `to_pil` here. We can expect that images are already converted to tensors before being passed to `RFFT2D`. I think you can completely remove the `__init__` method.

```suggestion
```

2024-10-04 13:33 UTC, guarin approved these changes
This looks great, thanks a lot for your contribution!

2024-10-04 13:33 UTC, merged

2024-10-04 13:48 UTC, snehilchatterjee commented
Thanks for letting me contribute! Looking forward to contributing more :smiley: