Removing Open CV dependencies
lightly-ai/lightly pull request #1679
Opened 2024-10-07 13:40 UTC by ishaanagw

2024-10-07 13:41 UTC, ishaanagw commented
Partly fixes - https://github.com/lightly-ai/lightly/issues/1477

2024-10-08 06:55 UTC, guarin requested changes
Thanks for the PR! I believe the videos are not correctly saved, left some comments :)

2024-10-08 06:55 UTC, guarin commented on tests/data/test_VideoDataset.py
> +            out = torchvision.io.write_video(path, self.frames_over_videos, frames)
```suggestion
            out = torchvision.io.write_video(filename=path, video_array=frames, fps=1)
```

`self.frames_over_videos` is a list of videos and we want to save every video individually.

2024-10-08 06:55 UTC, guarin commented on tests/data/test_VideoDataset.py
> +            out = torchvision.io.write_video(path, self.frames, n_frames_per_video)
```suggestion
            out = torchvision.io.write_video(filename=path, video_array=self.frames, fps=1)
```

2024-11-22 12:04 UTC, vectorvp commented
@guarin, is there a way I can help with completing this PR?

2024-11-22 12:23 UTC, guarin commented
Hi, yes that would be very helpful. You can merge the changes from this branch into your fork and make a new PR if that is ok?

2024-11-22 12:41 UTC, vectorvp commented
@guarin, sure. Are you online during weekends?

2024-11-22 12:42 UTC, guarin commented
I'm usually only available during weekdays

2024-12-03 08:19 UTC, guarin commented
This has been fixed in #1743

2024-12-03 08:19 UTC, closed without merging