cleaning up docs in lightly/data subpackage
lightly-ai/lightly pull request #1689
Opened 2024-10-09 18:22 UTC by ChiragAgg5k

Hey there, 

For now i have updated the docs for the helper functions only, and needed some review before i finish up with rest. Do let me know if you would like some modifications. I will finish up with rest very soon. Thanks :)

2024-10-09 18:26 UTC, ChiragAgg5k commented
<img width="1244" alt="Screenshot 2024-10-09 at 11 56 00 PM" src="https://github.com/user-attachments/assets/070514f7-bcf2-4916-a28f-5d462d5e2eb1">

i forgot to run the pre-commit, but now that i did, seems like everyone else also forgot to do so?? 😅

2024-10-10 07:15 UTC, guarin requested changes
Thanks a lot for the PR, this looks very good! Just one small comment but otherwise this is ready to be merged.

Interesting that the pre-commit hooks try to format the `openapi_generated` files, those should be left untouched.

2024-10-10 07:15 UTC, guarin commented on lightly/data/_helpers.py
> +                    but VideoDataset is not available.
```suggestion
        ValueError: If the specified dataset directory doesn't exist or if videos are present
            but VideoDataset is not available.
```

We usually don't align indents but instead just indent one level more.

2024-10-10 07:20 UTC, guarin commented
The Code Format Check action is failing, could you run `make format` and update the PR?

2024-10-10 09:17 UTC, guarin approved these changes
LGTM thanks so much!

2024-10-10 09:19 UTC, merged