Patch eval metrics to markdown
lightly-ai/lightly pull request #1706
Opened 2024-10-22 19:29 UTC by EricLiclair

- adds changes to return metrics from evals
- prints converted metrics to markdown

2024-10-23 06:56 UTC, guarin requested changes
Thanks a lot for your PR! I left some comments on how I believe we could simplify it a bit but the code overall looks very good.

2024-10-23 06:56 UTC, guarin commented on benchmarks/imagenet/vitb16/main.py
> +        eval_metrics: EvalMetrics = []
What do you think about aggregating all the metrics in a simple dictionary?

```suggestion
        eval_metrics = {}
```

2024-10-23 06:56 UTC, guarin commented on benchmarks/imagenet/vitb16/main.py
> +            for k, v in knn_eval.knn_eval(
```suggestion
            eval_metrics["knn"] = knn_eval.knn_eval(
```

2024-10-23 06:56 UTC, guarin commented on benchmarks/metrics.py
> +    return "\n".join(lines)
Let's move this function to the `main.py` files for now even if we have to duplicate it. The goal for the benchmarks is that the code is as simple as possible to make them easy to understand and modify.

We might have to rework some of the benchmarking soon, there were some changes regarding metrics in PyTorch Lightning that could simplify our code as well. AFAIK the `trainer.validate()` functions now return the metrics directly which means we won't have to rely on the callback anymore.

2024-10-23 06:56 UTC, guarin commented on benchmarks/metrics.py
It would be great if we could remove the need for this file completely to keep everything as simple as possible.

2024-10-23 08:08 UTC, EricLiclair commented on benchmarks/metrics.py
sure. I was first planning to integrate the metric's classes in the lib itself and expose an api to convert the metrics to markdown which would've required scoping + understanding the complete metrics flow. But yes, i agree we can keep it simple. let me add a commit considering the suggestions.

2024-10-24 07:30 UTC, guarin approved these changes
Thanks so much, this looks great!

2024-10-24 07:36 UTC, merged