Object detection scorer
lightly-ai/lightly pull request #252
Opened 2021-03-19 14:42 UTC by IgorSusmelj

### Changes
- Added the framework for computing scores for object detection predictions
- Add the scorer for "frequency-detection" which prefers images with many objects and diverse objects

2021-03-19 14:57 UTC, philippmwirth requested changes
Looks good, I have some minor feedback.

One thing I'd also like to discuss: We're requesting a rather specific format, I know that for example torchvision FasterRCNN provides a different output. Maybe we should already anticipate this and think about which is the most general type of boxes we can get -> make this the parent class and then have the others inherit from that. What do you think?

2021-03-19 14:57 UTC, philippmwirth commented on lightly/active_learning/scorers/detection.py
> +                      frequency_pentaly: float,
"pentaly" ;)

2021-03-19 15:29 UTC, IgorSusmelj commented
> Looks good, I have some minor feedback.
> 
> One thing I'd also like to discuss: We're requesting a rather specific format, I know that for example torchvision FasterRCNN provides a different output. Maybe we should already anticipate this and think about which is the most general type of boxes we can get -> make this the parent class and then have the others inherit from that. What do you think?

I like the idea of being more flexible. But there are so many options in object detection. I feel the best way is to have a clear format we want but help the user get there. Maybe we could offer some helper functions to the user. E.g. to change bounding box representation (x1, y1, x2, y2) --> (x1, y1, w, h).
Do you think that would work?

2021-03-19 15:32 UTC, IgorSusmelj commented on lightly/active_learning/scorers/detection.py
> +            A dictionary containing additional parameters for the scorers.
I will add one

2021-03-19 15:32 UTC, IgorSusmelj commented on lightly/active_learning/scorers/detection.py
> +                      frequency_pentaly: float,
arrgh, will fix this :)

2021-03-19 15:44 UTC, philippmwirth commented
> I like the idea of being more flexible. But there are so many options in object detection. I feel the best way is to have a clear format we want but help the user get there. Maybe we could offer some helper functions to the user. E.g. to change bounding box representation (x1, y1, x2, y2) --> (x1, y1, w, h).
> Do you think that would work?

I think there are many approaches we could take there:
- Bounding Box Class for each type of possible bbox and all provide the necessary functions for our scorer.
- Scorer Class for each type of possible bbox and all calculate the scores they can
- Helper functions which make it easy for the user to switch between formats

I would prefer the first one but maybe this should be covered in a different ticket.

2021-03-19 23:17 UTC, IgorSusmelj commented
> > I like the idea of being more flexible. But there are so many options in object detection. I feel the best way is to have a clear format we want but help the user get there. Maybe we could offer some helper functions to the user. E.g. to change bounding box representation (x1, y1, x2, y2) --> (x1, y1, w, h).
> > Do you think that would work?
> 
> I think there are many approaches we could take there:
> 
> * Bounding Box Class for each type of possible bbox and all provide the necessary functions for our scorer.
> * Scorer Class for each type of possible bbox and all calculate the scores they can
> * Helper functions which make it easy for the user to switch between formats
> 
> I would prefer the first one but maybe this should be covered in a different ticket.

Let's discuss this further in another issue. I'm also not sure where to put it. To `utils`? I would prefer 1 or 3. I could imagine that the 3rd option could be the easiest to implement. A few methods to transform the bounding boxes. I'm not sure a class would help.

2021-03-19 23:22 UTC, IgorSusmelj commented
I created an issue for the further discussion: https://github.com/lightly-ai/lightly/issues/253

2021-03-20 08:24 UTC, philippmwirth approved these changes

2021-03-21 16:09 UTC, merged