132 Docs on embeddings upload
lightly-ai/lightly pull request #303
Opened 2021-04-19 16:09 UTC by philippmwirth

# Docs on embeddings upload

Closes #132. 

- Fixed the api workflow client docstrings and added them to the autodocs.
- Showcased how to save embeddings and upload them from Python code
- Showcased how to upload images from a Python

2021-04-19 16:40 UTC, MalteEbner approved these changes

2021-04-20 08:43 UTC, IgorSusmelj commented on docs/source/getting_started/platform.rst
> +    # change mode to thumbnails or meta if you're working with sensitive data
would put thumbnails and meta in quotes (e..g 'thumbnails', 'meta') to make it clear

2021-04-20 08:44 UTC, IgorSusmelj commented on docs/source/getting_started/platform.rst
> +    client.upload_embeddings('embeddings.csv', name='my-embeddings')
Maybe mention/ make it more clear that we need to store the embeddings to a file first. We can't just upload a numpy array from memory.

2021-04-20 08:45 UTC, IgorSusmelj requested changes
Would clarify a bit the descriptions. Otherwise very good :)

2021-04-21 08:05 UTC, IgorSusmelj approved these changes

2021-04-21 09:18 UTC, merged