Add Jigsaw trasformation
lightly-ai/lightly pull request #477
Opened 2021-08-30 04:02 UTC by shikharmn

Jigsaw transformation returns n_grid random crops from the input image. This augmentation is essential for multiple Self Supervised Learning tasks.

2021-08-30 08:55 UTC, IgorSusmelj commented
This looks great thanks! Could you add an example of how to use it?

2021-08-30 11:32 UTC, shikharmn commented
Yeah, sure. Where exactly should I add this example?

2021-08-30 17:05 UTC, shikharmn commented
I've added an example usage to the jigsaw.py file as I've seen in other parts of the code, do let me know if this works.

2021-09-01 08:34 UTC, IgorSusmelj commented on tests/transforms/test_Jigsaw.py
> +class TestGaussianBlur(unittest.TestCase):
rename to `TestJigsaw`

2021-09-01 08:36 UTC, IgorSusmelj requested changes
Please rename the class for the test. Otherwise this looks great and we can merge it :)
Thanks a lot!

2021-09-01 08:39 UTC, shikharmn commented
Oops, done.

2021-09-02 09:46 UTC, IgorSusmelj approved these changes

2021-09-02 09:46 UTC, merged