added network traffic notes to docker with datasource
lightly-ai/lightly pull request #770
Opened 2022-04-19 14:48 UTC by MalteEbner

## Description
- Tell again to use the same region of a cloud provider
- Tell how much download/upload is needed

## Measured download usage for s3_aquarium
![image](https://user-images.githubusercontent.com/20324507/164031632-740df38a-c34d-4919-b5ba-dfd2d58b1088.jpeg)
## Measured usage for videos
See https://github.com/lightly-ai/lightly-core/pull/1501

2022-04-20 08:08 UTC, IgorSusmelj requested changes
This is great and super helpful. Left a few comments to make it easier to understand.

2022-04-20 08:08 UTC, IgorSusmelj commented on docs/source/docker/integration/docker_with_datasource.rst
> +- Uploading the report needs a few MB.
Drop as well

2022-04-20 08:08 UTC, IgorSusmelj commented on docs/source/docker/integration/docker_with_datasource.rst
> +
What's missing here is some sort of upper boundary. E.g. if you use all the features of Lightly you will create download traffic from your cloud storage equivalent to (training epochs + 5) x bucket size in GBytes.

And give an example: If you have a dataset consisting of 500'000 images of size 10 GBytes and run Lightly with training an SSL model for 10 epochs you will face at most (10 + 5) x 10 GBytes = 150 GBytes of download traffic.

2022-04-20 08:08 UTC, IgorSusmelj commented on docs/source/docker/integration/docker_with_datasource.rst
> +Depending on the video format, downloading a full video might be necessary to download a single frame.
Rephrase the first sentence and put it into an info box:

Depending on the video format, downloading a full video might be necessary to download a single frame. --> Depending on the video format, downloading a single frame might require downloading the entire video.

2022-04-20 08:08 UTC, IgorSusmelj commented on docs/source/docker/integration/docker_with_datasource.rst
> +Thus downloading x frames from y different videos might download all y videos in worst case.
I'd personally go for upper case variables in a text block like this. 
x --> X
y --> Y
...

2022-04-20 08:08 UTC, IgorSusmelj commented on docs/source/docker/integration/docker_with_datasource.rst
> +- Embedding and pretagging each download the non-corrupt dataset.
Split embedding and pretagging to its own line

2022-04-20 08:08 UTC, IgorSusmelj commented on docs/source/docker/integration/docker_with_datasource.rst
> +  As loading single frames into the Lightly Platform is not possible, the selected frames are uploaded to it.
Again here. We don't care about upload traffic for this analysis

2022-04-20 08:08 UTC, IgorSusmelj commented on docs/source/docker/integration/docker_with_datasource.rst
> +- Creating the report with images overlayed in the scatterplot will download about 50 frames.
Again, drop the 50 images

2022-04-20 08:08 UTC, IgorSusmelj commented on docs/source/docker/integration/docker_with_datasource.rst
> +- Uploading the report needs a few MB.
Drop report here as well

2022-04-20 08:08 UTC, IgorSusmelj commented on docs/source/docker/integration/docker_with_datasource.rst
> +
Also here make please a quick summary with an upper bound and add an example.

2022-04-20 21:42 UTC, MalteEbner commented on docs/source/docker/integration/docker_with_datasource.rst
>            `degraded transfer speeds and additional costs will be incurred by AWS <https://aws.amazon.com/premiumsupport/knowledge-center/s3-transfer-data-bucket-instance/>`_!
The whole file is called "Using the docker with an S3 bucket as remote datasource". Also other tutorials for docker only cover the S3 case
We need to update that, but I would not feature-creep it into this issue. I created a separate issue for it: https://linear.app/lightly/issue/LIG-1020/datasource-docs-docker-add-gcs-and-azure

2022-04-20 21:42 UTC, MalteEbner commented on docs/source/docker/integration/docker_with_datasource.rst
> +the same there can be `degraded transfer speeds and additional costs will be incurred by AWS <https://aws.amazon.com/premiumsupport/knowledge-center/s3-transfer-data-bucket-instance/>`_!
See https://github.com/lightly-ai/lightly/pull/770#discussion_r854577272

2022-04-21 07:11 UTC, MalteEbner commented on docs/source/docker/integration/docker_with_datasource.rst
> +The worker causes significant network traffic at the following steps:
Yes, this is why I added "significant". I want to make clear that this does not list ALL network traffic, but only the steps needing significant network traffic.

2022-04-21 07:31 UTC, IgorSusmelj approved these changes

2022-04-21 07:58 UTC, merged