Guarin lig 1010 multiple object level run docs
lightly-ai/lightly pull request #772
Opened 2022-04-21 09:13 UTC by guarin

* Update docker configuration
* Add information about crop dataset naming to object level docs

2022-04-22 07:39 UTC, philippmwirth requested changes
Somehow this doesn't contain any concrete information about how to run the workflow twice, does it?

2022-04-22 07:39 UTC, philippmwirth commented on docs/source/docker/advanced/object_level.rst
> +If you uploaded the predictions to `.lightly/predictions/vehicles_object_detections`
You could add an `E.g.` here

2022-04-25 08:18 UTC, guarin commented on docs/source/docker/advanced/object_level.rst
> +If you uploaded the predictions to `.lightly/predictions/vehicles_object_detections`
Thanks, added it :)

2022-04-25 08:19 UTC, guarin commented
> Somehow this doesn't contain any concrete information about how to run the workflow twice, does it?

Yes, I did not add it first because by default it should just work. But I added a small section that explains it, hope it is understandable :)

2022-04-25 08:24 UTC, philippmwirth approved these changes
looks good!

2022-04-25 08:24 UTC, merged