Guarin lig 1055 dcl decoupled contrastive learning
lightly-ai/lightly pull request #793
Opened 2022-05-11 12:08 UTC by guarin

* Add DCL loss
* Add DCLW loss
* Add DCL & DCLW examples

2022-05-11 13:32 UTC, philippmwirth requested changes
I only found one typo, other than that this looks great!

2022-05-11 13:36 UTC, philippmwirth commented
> There is one outstanding question regarding the weighting function in DCLW. I think the output tensors passed to the weighting function should be detached but the paper does not mention it. In my opinion the weighting function should just scale the loss and not be backpropagated. I'll run a test with and without detaching to see what happens.

Curious to see the results 👍

2022-05-11 18:11 UTC, IgorSusmelj requested changes
This looks very good. I added a few suggestions. The only thing I'd def. do is explain some of the comments more and write out the code for the benchmarks.

2022-05-11 18:11 UTC, IgorSusmelj commented on lightly/loss/dcl_loss.py
> +    return 2 - out0.shape[0] * torch.nn.functional.softmax(similarity, dim=0)
You can `import torch.nn as nn` as it's a common PyTorch convention. That might shorten some of the lines in the file. (not a must but more a suggestion)

2022-05-11 18:11 UTC, IgorSusmelj commented on lightly/loss/dcl_loss.py
> +        weight_fn: Optional[Callable[[Tensor, Tensor], Tensor]] = None,
If we add such "complex" type hints I'd expect somewhere examples/ explanations on what this means. Ideally, above where you describe the attribute.

2022-05-11 18:11 UTC, IgorSusmelj commented on lightly/loss/dcl_loss.py
> +                all processes.
Add/ mention that "all processes" is for distributed processing (e.g. from all GPUs)

2022-05-11 20:40 UTC, IgorSusmelj commented
And please don't forget to update readme, docs etc.

2022-05-12 08:25 UTC, guarin commented on lightly/loss/dcl_loss.py
> +        out0 = out0_all = torch.nn.functional.normalize(out0, dim=1)
> Also, what would be the reason to have self.gather_distributed == False?

You can save some communication overhead between the gpus. And it also does not break training if you forget by accident to use a [distributed sampler](https://pytorch.org/docs/stable/data.html#torch.utils.data.distributed.DistributedSampler) when training with multiple gpus.

2022-05-13 07:59 UTC, guarin commented
I updated the pr with the suggested changes. I also added full example code for dcl to the docs, this should make it more consistent with the other examples.

[DCL & DCLW — lightly 1.2.14 documentation.pdf](https://github.com/lightly-ai/lightly/files/8685238/DCL.DCLW.lightly.1.2.14.documentation.pdf)

I am still running the benchmark with DCLW and detached weight calculation. Will add the values later.

2022-05-16 07:43 UTC, guarin commented
Added the benchmark results, runtime is somehow slower than for previous runs on the large gpu.

2022-05-17 08:14 UTC, IgorSusmelj approved these changes
Looks great!

2022-05-17 11:06 UTC, philippmwirth approved these changes

2022-05-17 11:18 UTC, merged