Lig 1593 part2
lightly-ai/lightly pull request #896
Opened 2022-08-10 16:24 UTC by japrescott

fixes lig-1593
- ensure to only set s3 headers for server side encryption if we are actually talking to s3 as google buckets doesn't like headers of other buckets

2022-08-10 17:20 UTC, MalteEbner requested changes
In general, this makes some nice improvements! You can resolve my appreciations if needed.

However, I would rework and unittest the `get_signed_url_destination` function.

2022-08-10 17:20 UTC, MalteEbner commented on lightly/api/utils.py
> +def get_signed_url_destination(signed_url: str)->DatasourceType:
I would write a unittest for this.

2022-08-11 06:35 UTC, japrescott commented on lightly/api/utils.py
> +    if signed_url.find('storage.googleapis.com/')!=-1 and  signed_url.find('boris-platform-')!=-1:
good point it was a mindless copy+paste from the UI

2022-08-11 06:39 UTC, japrescott commented on lightly/api/utils.py
> +    if signed_url.find('storage.googleapis.com/')!=-1 and  signed_url.find('boris-platform-')!=-1:
hmmkey but its not nullsafe. I will default the param

2022-08-11 06:58 UTC, japrescott commented on lightly/api/utils.py
> +def get_signed_url_destination(signed_url: str)->DatasourceType:
done

2022-08-11 11:27 UTC, MalteEbner approved these changes

2022-08-12 08:47 UTC, MalteEbner approved these changes
Great :)

2022-08-12 09:00 UTC, merged