Fix typehints for export functions
lightly-ai/lightly pull request #948
Opened 2022-10-04 14:06 UTC by philippmwirth

# Fix typehints for export functions

The typehints for the export functions are inaccurate because swagger codegen can't handle arrays of types correctly.

2022-10-04 14:08 UTC, japrescott requested changes

2022-10-04 14:08 UTC, japrescott commented on lightly/api/api_workflow_download_dataset.py
> +    ) -> List[Dict]:
@MalteEbner made me add this all over the place.. if you really need to remove these, you'll also need to remove them from the tests and mocked stuff

2022-10-04 14:46 UTC, michal-lightly commented
I have a few questions (but maybe someone has more context and can approve).
1. What is the error/problem caused by the incorrect types?
2. `LabelBoxDataRow` seems more concrete than `Dict`. Why is Dict the proper type?

It would also be nice to specify the Dict type (Dict[str, Any]?)

2022-10-04 15:01 UTC, philippmwirth commented
> I have a few questions (but maybe someone has more context and can approve).
> 
>     1. What is the error/problem caused by the incorrect types?
> 
>     2. `LabelBoxDataRow` seems more concrete than `Dict`. Why is Dict the proper type?
> 
> 
> It would also be nice to specify the Dict type (Dict[str, Any]?)

There's no error caused by the incorrect types other than that the information provided is faulty because the functions actually return dictionaries. This should also answer your second question: Dict is the proper type because that's what the function actually returns. An alternative solution would be to define the types `LabelBoxDataRows` as `Dict[str, Any]` but then there's ambiguity because `LabelBoxDataRows`  actually exists as a type (it's just not used).

2022-10-05 13:26 UTC, japrescott approved these changes

2022-10-05 13:32 UTC, michal-lightly approved these changes
Lightly PIP package is not type-checked anyway.

2022-10-05 13:34 UTC, merged